### ISSUE TITLE
User-service has issues sending request to email-service

### ISSUE THREAD

**Issue by ryanchua00** [CS3219-AY2324S1/ay2324s1-course-assessment-g58#104]
See error log

![image](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g58/assets/62086995/38742b69-c36b-47f8-91ab-43cce5f93562)

**Comment by tobihy** [comment]
Are you passing invitation_id/user_id into json.stringify? 

Invitation_id/user_id may be of type bigint in the schema, so you may have to either change it to another type or exclude from the raw data.

Ran into this issue when making calls to the user service last time as well.

**Comment by ryanchua00** [comment]
Fixed, issue with old data
