### ISSUE TITLE
Should we rename `mongodb-database` created by @Varstak into `question-service` so that it is more consistent with the rest of the services?

### ISSUE THREAD

**Issue by ryanchua00** [CS3219-AY2324S1/ay2324s1-course-assessment-g58#38]
Should we rename `mongodb-database` created by @Varstak into `question-service` so that it is more consistent with the rest of the services?

Other than that, LGTM 👍

_Originally posted by @tobihy in https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g58/issues/35#issuecomment-1742562228_
           
Maybe we can clean the naming and file system after Assignment 5!

**Comment by bokuanT** [comment]
yes i concur
